package com.example.course_service.Models;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "enrollments")
public class Enrollment {
    @Id
    private String enrollmentId;
    private String studentId;
    private List<Course> courseList;
    private LocalDate enrollmentDate; // Optional, can be generated by the service
}
