package com.example.course_service.Dtos;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class EnrollmentRequest {
    private String studentId;
    private String courseId;
    private LocalDate enrollmentDate; // Optional, can be generated by the service
}
